### ISSUE TITLE
Only support for local execution?

### ISSUE THREAD

**Issue by johanneshofer1** [MobiSense/SwarmMap#1]
Is there already an implementation in which clients and servers do not run locally on a device, but communicate over a network?

My understanding of the current swarm_map executable is the following:

One SLAM instance and one ClientMediator is created per client. The server is only represented by a GlobalMediator (=ClientMediator). These are all executed locally. Only the SLAM and ClientMediator instances per client are connected via a ConnectionService.  Subsequently, each client executes SLAM normally. The updates of the cards are distributed in certain time intervals (500ms) by the MediatorScheduler. 

My goal would be an implementation where one client instance is running per machine and one server is connected to all of them. 
Does such an example already exist?

**Comment by Halcao** [comment]
We are currently refactoring the separated version, because some actual deployment details of the production at the oil-field need to be hidden.

**Comment by Halcao** [comment]
We have released the standalone mode, which has a convenient network connection approach (detailed in the README.md). Please check it out. @johanneshofer1
